### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by rodneyosodo** [JKUATSES/2021-DesignMechanicalSystem#1]
Make sure you have 

- [x] Well documented README
- [x] Podcast recording
- [x] Youtube recording if necessary
- [ ] Blogpost article

**Comment by YvonneMureithi** [comment]
Blog post article still in progress.
We can do the podcast recording on Monday or Tuesday next week.
Still updating the README file.

**Comment by rodneyosodo** [comment]
- Let's do the podcast on Monday
- We will probably record the session during Thursday as some of the members said they would like to refer after
- Finish up on the readme

**Comment by rodneyosodo** [comment]
Please write the blog post article

**Comment by YvonneMureithi** [comment]
Is there a blog post sample I can use to refer to, i.e. of a project done?

Kind Regards,
Yvonne Mureithi.

**Comment by rodneyosodo** [comment]
You can check out:
- [Blog article for Africastalking](https://developers.decoded.africa/index.php/2021/05/09/smart-farm-with-africastalking-iot-platform/)
- [Ses blog](http://ses.jkuat.ac.ke/blog/)

**Comment by YvonneMureithi** [comment]
Will do, thanks.

Kind Regards,
Yvonne Mureithi.
