### ISSUE TITLE
Stress Analysis

### ISSUE THREAD

**Issue by rodneyosodo** [JKUATSES/2021-DesignMechanicalSystem#3]
- [x] Analyze the stresses in pressure vessels, press fits, curved beams, bolts, and bolted joints in your system
- [x] Calculate stress in machine components due to combined loadings.

**Comment by YvonneMureithi** [comment]
Stress analysis of the Mechanical Compenent is complete.

No pressure vessels, press fits, curved beams and bolts in the system.

**Comment by rodneyosodo** [comment]
Let me check

**Comment by rodneyosodo** [comment]
That is great.
